<?php

namespace app\admin\controller;

class Admin extends Common {
    //
    protected $db;

    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Admin();
    }

    // 用户列表
    public function index() {
        $field = $this->db->getAll();
        $this->assign('field', $field);
        return $this->fetch();
    }

    // 添加用户
    public function store() {
        if (request()->isPost()) {
            $res = $this->db->store(input('post.'));
            if ($res['valid']) {
                $this->success($res['msg'], 'index');
                exit;
            } else {
                $this->error($res['msg']);
                exit;
            }
        }
        return $this->fetch();
    }

    // 编辑用户
    public function edit() {
        $id = input('param.id/d');

        if (request()->isPost()) {
            $res = $this->db->edit(input('post.'));
            if ($res['valid']) {
                $this->success($res['msg'], 'index');
                exit;
            } else {
                $this->error($res['msg']);
                exit;
            }
        }

        // 查询用户信息
        $oldData = $this->db->find($id);
        $this->assign('oldData', $oldData);
        return $this->fetch();
    }

    // 禁用、恢复 用户
    public function show() {
        $res = $this->db->show(input('get.id/d'), input('get.handle/d'));
        if ($res['valid']) {
            $this->success($res['msg'], 'index');
            exit;
        } else {
            $this->error($res['msg']);
            exit;
        }
    }

    // 删除用户
    public function del() {
        $res = $this->db->del(input('get.id/d'));
        if ($res['valid']) {
            $this->success($res['msg'], 'index');
            exit;
        } else {
            $this->error($res['msg']);
            exit;
        }
    }

    // 设置用户分组
    public function setGroup() {
        if (request()->isPost()) {
            $res = $this->db->setGroup(input('post.'));
            if ($res['valid']) {
                $this->success($res['msg']);
                exit;
            } else {
                $this->error($res['msg']);
                exit;
            }
        }

        // 管理员 ID
        $admin_id = input('param.id/d');

        // 获取管理员信息
        $adminData = $this->db->field('id,name')->find($admin_id);
        $this->assign('adminData', $adminData);

        // 获取当前已分组的 ID
        $accessData = db('admin_group')->where('admin_id', $admin_id)->column('group_id');
        $this->assign('accessData', $accessData);

        // 获取分组信息
        $groupData = db('group')->where('status', 1)->select();
        $this->assign('groupData', $groupData);

        return $this->fetch();
    }
}
