<?php

namespace app\admin\controller;

use houdunwang\arr\Arr;

class Group extends Common {
    //
    protected $db;

    protected function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Group();
    }

    // 分组首页
    public function index() {
        $field = $this->db->getAll();
        $this->assign('field', $field);
        return $this->fetch();
    }

    // 添加、编辑分组
    public function store() {
        $id = input('param.id/d');
        if (request()->isPost()) {
            $res = $this->db->store(input('post.'));
            if ($res['valid']) {
                $this->success($res['msg'], 'index');
                exit;
            } else {
                $this->error($res['msg']);
                exit;
            }
        }

        if ($id) {
            // 编辑获取 旧数据
            $oldData = $this->db->find($id);
        } else {
            $oldData = ['gname' => ''];
        }
        $this->assign('oldData', $oldData);
        return $this->fetch();
    }

    // 编辑分组
    public function edit() {
        return $this->fetch();
    }

    // 禁用、恢复 用户
    public function changeStatus() {
        $res = $this->db->changeStatus(input('get.id/d'), input('get.handle/d'));
        if ($res['valid']) {
            $this->success($res['msg'], 'index');
            exit;
        } else {
            $this->error($res['msg']);
            exit;
        }
    }

    // 删除分组
    public function del() {
        $res = $this->db->del(input('get.id/d'));
        if ($res['valid']) {
            $this->success($res['msg'], 'index');
            exit;
        } else {
            $this->error($res['msg']);
            exit;
        }
    }

    // 给用户组分配权限
    public function setAuth() {

        if (request()->isPost()) {
            $res = $this->db->setAuth(input('post.'));
            if ($res['valid']) {
                $this->success($res['msg']);
                exit;
            } else {
                $this->error($res['msg']);
                exit;
            }
        }

        // 管理员 ID
        $group_id = input('param.id/d');

        // 获取组信息
        $groupData = $this->db->field('id,gname,rules')->find($group_id);
        $this->assign('groupData', $groupData);

        // 将当期分组规则转为数组
        $accessData = explode(',', $groupData['rules']);
        $this->assign('accessData', $accessData);

        // 获取所有规则数据
        $rulesData = Arr::tree(db('rules')->select(), 'rname', 'id', 'pid');
        $this->assign('rulesData', $rulesData);

        return $this->fetch();
    }
}
