<?php

namespace app\admin\controller;

class Rules extends Common {
    //
    protected $db;

    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Rules();
    }

    // 权限列表
    public function index() {
        $rules = $this->db->getAll();
        $this->assign('rules', $rules);
        return $this->fetch();
    }

    // 添加权限
    public function store() {
        if (request()->isPost()) {
            $res = $this->db->store(input('post.'));
            if ($res['valid']) {
                $this->success($res['msg'], 'index');
                exit;
            } else {
                $this->error($res['msg']);
                exit;
            }
        }
        return $this->fetch();
    }

    // 添加子权限
    public function addSon() {
        if (request()->isPost()) {
            $res = $this->db->store(input('post.'));
            if ($res['valid']) {
                $this->success($res['msg'], 'index');
                exit;
            } else {
                $this->error($res['msg']);
                exit;
            }
        }

        $id = input('param.id/d');
        $data = $this->db->find($id);
        $this->assign('data', $data);

        return $this->fetch();
    }

    // 编辑权限
    public function edit() {
        if (request()->isPost()) {
            $res = $this->db->edit(input('post.'));
            if ($res['valid']) {
                $this->success($res['msg'], 'index');
                exit;
            } else {
                $this->error($res['msg']);
                exit;
            }
        }

        $id = input('param.id/d');
        $oldData = $this->db->find($id);
        $this->assign('oldData', $oldData);

        $rulesData = $this->db->getRulesData($id);
        $this->assign('rulesData', $rulesData);

        return $this->fetch();
    }

    // 删除权限
    public function del() {
        $res = $this->db->del(input('get.id/d'));
        if ($res['valid']) {
            $this->success($res['msg'], 'index');
            exit;
        } else {
            $this->error($res['msg']);
            exit;
        }
    }
}
