<?php

namespace app\admin\controller;

class Webset extends Common {
    //
    protected $db;

    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Webset();
    }

    // 首页
    public function index() {
        $data = $this->db->select();
        foreach ($data as &$v) {
            $v['webset_value'] = htmlspecialchars($v['webset_value']);
        }
        $this->assign('data', $data);
        return $this->fetch();
    }

    // 编辑
    public function edit() {
        if (request()->isAjax()) {
            $res = $this->db->edit(input('post.'));
            if ($res['valid']) {
                $this->success($res['msg'], 'index');
                exit;
            } else {
                $this->error($res['msg']);
                eixt;
            }
        }
    }
}
