<?php

namespace app\index\controller;


class Details extends Common {
    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index() {
        $aid = input('param.aid');
        return $this->fetch();
    }

}
