<?php

namespace app\index\controller;


class Lists extends Common {
    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index() {
        $cid = input('param.cid');
        if ($cid == 24) {
            return $this->fetch('actList');
        } else if (in_array($cid, [16, 17, 18, 19, 20])) {
            return $this->fetch('caseList');
        }
    }
}
