<?php

namespace app\index\controller;


class Special extends Common {
    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    // 首页
    public function index() {
        return $this->fetch();
    }

}
